extension:
  - ts
spec: 
  # - test/**/*.test.ts
  - test/run/single-runner.test.ts
require: 
  - ts-node/register
  - source-map-support/register.js
  - test/tests-global-fixture.js
loader: ts-node/esm
watch-files:
  - src
  - test
watch-ignore:
  - test/playground
  - test/express.lock
timeout: 5000
