extension:
  - ts
spec: 
  - test/**/*.test.ts
require: 
  - ts-node/register
  - test/tests-global-fixture.js
loader: ts-node/esm
watch-files:
  - src
  - test
watch-ignore:
  - test/playground
timeout: 5000
